name = "QuantumReservoirComputing"
uuid = "b30e0d2c-b786-4f26-b83a-6ae7ebd01348"
authors = ["Zakari Denis", "Laboratoire MPQ"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
